-  hosts: localhost
   gather_facts: no
   module_defaults:
    group/aws:
      region: "us-east-2"
   tasks:
    - name: create a postgres user for Postgres RDS with a random password using only ascii letters
        user:
          name: postgres
          password: "{{ lookup('password', '/tmp/postgres_user.txt chars=ascii_letters') }}"
        register: postgres_user
    - name: create a image_gallery user for Postgres RDS with a random password using only ascii letters
        user:
          name: image_gallery
          password: "{{ lookup('password', '/tmp/image_gallery_user.txt chars=ascii_letters') }}"
      register: image_gallery_user
    - rds_subnet_group:
        state: present
        name: m5-rds-priv-dbgrp
        description: Module 5 Private Subnet Group
        subnets:
          - "{{ private_subnet.subnet.id }}"
          - "{{ private_subnet2.subnet.id }}"
      register: rds_subnet_group
    - rds:
        command: create
        instance_name: m5-ansible-image-gallery-rds
        db_engine: postgres
        size: 10
        instance_type: db.t2.micro
        username: 
        password: "{{ lookup('file', '/tmp/postgres_user.txt') }}"
        vpc_security_groups: "{{ ig_postgres_sg.group_id }}"
        subnet: "{{ rds_subnet_group.subnet_group.name }}"
        wait: yes
        wait_timeout: 550
        region: us-east-2
        zone: us-east-2b
        tags:
          Environment: production
          Name: Module 5 RDS
      register: rds_instance