-  hosts: localhost
    gather_facts: no
    vars:
      sec_postgres: {
          "username": "postgres",
          "password": "simple", #"{{ pg_user_pass }}",
          "engine": "postgres",
          "host": "{{ rds_instance.instance.endpoint }}",
          "port": 5432,
          "dbInstanceIdentifier": "m5-ansible-image-gallery-rds",
          "db_name": "image_gallery"
        }
      sec_image_gallery: {
          "username": "image_gallery",
          "password": "simple", #"{{ pg_user_pass }}",
          "engine": "postgres",
          "host": "{{ rds_instance.instance.endpoint }}",
          "port": 5432,
          "dbInstanceIdentifier": "m5-ansible-image-gallery-rds",
          "db_name": "image_gallery"
        }
    module_defaults:
    group/aws:
      region: "us-east-2"
    tasks:
      aws_secret:
          name: 'sec-m5-postgres'
          state: present
          secret_type: 'string'
          secret: '{{ sec_postgres | to_json }}'
          
      aws_secret:
          name: 'sec-m5-image_gallery'
          state: present
          secret_type: 'string'
          secret: '{{ sec_image_gallery | to_json }}'