- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96" # TAKE THIS OUT OR SUB IT FOR SOMETHING USEFUL
  module_defaults: 
    group/aws: 
      region: "us-east-2"
  tasks:
    #- route53:
     #   state: absent
       # zone: sky-boston.com
      #  record: sky-boston.com
        #type: A
    - elb_network_lb:
        name: m5-ig-asg-lb
        state: absent
        wait: yes
        wait_timeout: 300
      

          
    