---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Obtain domain certificate information
      aws_acm_info:
        domain_name: "sky-boston.com"
      register: domain_cert
    #- name:
      #debug:
        #msg: "{{ domain_cert.certificates[0].certificate_arn }}"
...